I add in some testing and keys to the text and button, and I added some screen and functionality
crzaratech/rent_tech_app pull request #21
Opened 2021-11-29 06:57 UTC by JosefADVassell

2021-11-29 17:57 UTC, LeoRuiz01 requested changes
Add comments to  shopping_cart_product.dart, checkout_screen.dart, rentedscreen.dart, buyaproduct (change the name to match the naming schema to match the other files i.e. rented_screen for both rentedscreen and buyproduct.). 

The reason comments are being requested is because this is a 930 line PR that doesn't include an explanation to what is going on. The comments should explain what is going on each file without being too complex. ( The comment should not be longer than 3 lines).

2021-11-29 17:57 UTC, LeoRuiz01 commented on lib/rent_a_product/buyaproduct.dart
> +                        child: Text("Rent $value")),*/
If this is not going to be used in the future, remove the comments from the file.

2021-11-29 23:35 UTC, LeoRuiz01 approved these changes
LGTM

2021-11-30 00:37 UTC, crzaratech approved these changes
Nice, but remember to make different PRs for different features. All the added features were good

2021-11-30 00:37 UTC, merged